name: test
on: push

jobs:
  test:
    name: test
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        runs-on: [ubuntu-20.04, macos-10.15, windows-2019]
    runs-on: ${{ matrix.runs-on }}

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -V || 1
          python3 -V || 1
          pwd
          python -m pip install poetry
          poetry update
          poetry install
      - name: Test with pytest
        run: poetry run pytest tests
